#!/bin/bash
# Set DB-related environment variables for Heroku deployment

echo "Setting DATABASE_URL environment variable to point to local conftech PostgreSQL database"
set DATABASE_URL="postgres://postgres:ConfTech42@localhost:5432/conftechlocaldb"
export DATABASE_URL="postgres://postgres:ConfTech42@localhost:5432/conftechlocaldb"

echo "Launching conftech API server"
foreman start
